# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('nocarnet', models.CharField(max_length=200)),
                ('encargado', models.CharField(max_length=200)),
                ('numencargado', models.CharField(max_length=200)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('aula', models.CharField(max_length=200)),
                ('capacidad', models.CharField(max_length=200)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Maestro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('dpi', models.CharField(max_length=200, unique=True)),
                ('nocuenta', models.CharField(max_length=200)),
                ('direccion', models.TextField(max_length=255)),
                ('especialidad', models.TextField()),
                ('salario', models.TextField()),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('periodos', models.CharField(max_length=200)),
                ('maestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.Maestro')),
            ],
        ),
        migrations.CreateModel(
            name='MateriasCursadas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punteo', models.TextField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.Alumno')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.Materia')),
            ],
        ),
        migrations.CreateModel(
            name='MateriasGrados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.Grado')),
                ('materias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.Materia')),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.Grado'),
        ),
    ]
