# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grado',
            name='materias',
            field=models.ManyToManyField(through='alumnos.MateriasGrados', to='alumnos.Materia'),
        ),
    ]
