# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_grado_materias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grado',
            name='materias',
        ),
        migrations.AddField(
            model_name='grado',
            name='materia',
            field=models.ManyToManyField(blank=True, to='alumnos.Materia'),
        ),
    ]
