# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_auto_20171121_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='MateriasGrados2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.Grado')),
                ('materias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.Materia')),
            ],
        ),
    ]
